{
 "title": "TrueNAS Scale / CGroups/Containers",
 "tags": [ "truenas" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(uptime,job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(uptime{job=\"$job\"},instance)"
    }
   },
   {
    "name": "cgroup",
    "label": "cgroup",
    "query": {
     "query": "label_values(cgroup_cpu_usage{instance=\"$instance\", job=\"$job\"},cgroup)"
    }
   },
   { "name": "smooth", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cgroup_cpu_limit{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU throttled",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cgroup_cpu_throttled{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cgroup_mem_utilization{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pagefaults",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cgroup_pgfaults{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cgroup_cpu_usage{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "cgroup_mem_usage{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "CPU pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cgroup_cpu_full_pressure{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "{{dimension}}"
    },
    {
     "expr": "cgroup_cpu_some_pressure{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "CPU stall time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cgroup_cpu_full_pressure_stall_time{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "full"
    },
    {
     "expr": "cgroup_cpu_some_pressure_stall_time{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "some"
    }
   ]
  },
  {
   "title": "Memory pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cgroup_mem_full_pressure{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "{{dimension}}"
    },
    {
     "expr": "cgroup_mem_some_pressure{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Memory stall time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cgroup_mem_full_pressure_stall_time{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "full"
    },
    {
     "expr": "cgroup_mem_some_pressure_stall_time{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "some"
    }
   ]
  },
  {
   "title": "IO pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cgroup_io_full_pressure{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "{{dimension}}"
    },
    {
     "expr": "cgroup_io_some_pressure{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "IO stall time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cgroup_io_full_pressure_stall_time{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "full"
    },
    {
     "expr": "cgroup_io_some_pressure_stall_time{job=\"$job\", instance=\"$instance\", cgroup=~\"$cgroup\"}",
     "legendFormat": "some"
    }
   ]
  }
 ]
}